[build]
  command = "solid-start build"
  functions = "netlify/functions"
  publish = "netlify"

[[redirects]]
  from = "/tv"
  to = "https://ghproxy.com/https://raw.githubusercontent.com/Cyril0563/lanjing_live/main/TVbox_Free/LIVE/Free/HD_LIVE.txt"
  status = 200
  force = true
[[redirects]]
  from = "https://voluble-arithmetic-dde72a.netlify.app/tv1"
  to = "https://www.100km.top/0"
  status = 302
  force = true # COMMENT: ensure that we always redirect
  
  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
